name: Train LunarLander Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gymnasium numpy torch

      - name: Train the agent
        run: |
          python train_agent.py --train --filename best_policy.pth

      - name: Upload trained model
        uses: actions/upload-artifact@v3
        with:
          name: best_policy
          path: best_policy.pth